import {
  exploreCategoryDataType,
  FeatureCardDataType,
} from "@/types/searchJob";

export const exploreCategoryData: exploreCategoryDataType[] = [
  {
    id: 1,
    icon: "/assets/searchJob/design.svg",
    category: "Design",
    totalJobs: 235,
  },
  {
    id: 2,
    icon: "/assets/searchJob/sales.svg",
    category: "Sales",
    totalJobs: 756,
  },
  {
    id: 3,
    icon: "/assets/searchJob/marketing.svg",
    category: "Marketing",
    totalJobs: 140,
  },
  {
    id: 4,
    icon: "/assets/searchJob/finance.svg",
    category: "Finance",
    totalJobs: 325,
  },
  {
    id: 5,
    icon: "/assets/searchJob/technology.svg",
    category: "Technology",
    totalJobs: 436,
  },
  {
    id: 6,
    icon: "/assets/searchJob/engineering.svg",
    category: "Engineering",
    totalJobs: 542,
  },
  {
    id: 7,
    icon: "/assets/searchJob/business.svg",
    category: "Business",
    totalJobs: 211,
  },
  {
    id: 8,
    icon: "/assets/searchJob/humanResource.svg",
    category: "Human Resource",
    totalJobs: 346,
  },
];

//featured Job

export const featureJobData: FeatureCardDataType[] = [
  {
    id: 1,
    jobRole: "Senior Software Engineer",
    company: "Amazon",
    companyDescription: "Leading e-commerce and cloud computing company",
    logo: "/covers/amazon.png",
    location: "Seattle, WA (Hybrid)",
    tags: ["AWS", "Cloud", "Full Stack", "Java", "Python"],
    salary: "$150K - $220K",
    type: "Full-time",
  },
  {
    id: 2,
    jobRole: "Product Designer",
    company: "Facebook",
    companyDescription: "Global social media and technology company",
    logo: "/covers/facebook.png",
    location: "Menlo Park, CA (Remote)",
    tags: ["UI/UX", "Product Design", "Figma", "Design Systems"],
    salary: "$140K - $200K",
    type: "Full-time",
  },
  {
    id: 3,
    jobRole: "DevOps Engineer",
    company: "Hostinger",
    companyDescription: "Web hosting and cloud solutions provider",
    logo: "/covers/hostinger.png",
    location: "Lithuania (Remote)",
    tags: ["Docker", "Kubernetes", "CI/CD", "Cloud Infrastructure"],
    salary: "$90K - $130K",
    type: "Full-time",
  },
  {
    id: 4,
    jobRole: "Frontend Engineer",
    company: "Pinterest",
    companyDescription: "Visual discovery platform for inspiration",
    logo: "/covers/pinterest.png",
    location: "San Francisco, CA (Hybrid)",
    tags: ["React", "TypeScript", "Next.js", "Web Performance"],
    salary: "$130K - $180K",
    type: "Full-time",
  },
  {
    id: 5,
    jobRole: "Mobile Developer",
    company: "Telegram",
    companyDescription: "Secure messaging and communication platform",
    logo: "/covers/telegram.png",
    location: "Dubai, UAE (Remote)",
    tags: ["iOS", "Android", "Swift", "Kotlin"],
    salary: "$100K - $160K",
    type: "Full-time",
  },
  {
    id: 6,
    jobRole: "Backend Engineer",
    company: "Reddit",
    companyDescription: "Community-driven content and discussion platform",
    logo: "/covers/reddit.png",
    location: "New York, NY (Hybrid)",
    tags: ["Python", "Django", "PostgreSQL", "Redis"],
    salary: "$140K - $190K",
    type: "Full-time",
  },
  {
    id: 7,
    jobRole: "Data Scientist",
    company: "Spotify",
    companyDescription: "Leading music and audio streaming platform",
    logo: "/covers/spotify.png",
    location: "Stockholm, Sweden (Hybrid)",
    tags: ["Machine Learning", "Python", "SQL", "Data Analytics"],
    salary: "$120K - $180K",
    type: "Full-time",
  },
  {
    id: 8,
    jobRole: "UI/UX Designer",
    company: "Adobe",
    companyDescription: "Creative software and digital experience leader",
    logo: "/covers/adobe.png",
    location: "San Jose, CA (Hybrid)",
    tags: ["Adobe XD", "Photoshop", "Design Systems", "Prototyping"],
    salary: "$130K - $170K",
    type: "Full-time",
  },
  {
    id: 9,
    jobRole: "Security Engineer",
    company: "Yahoo",
    companyDescription: "Global technology and media company",
    logo: "/covers/yahoo.png",
    location: "Sunnyvale, CA (Hybrid)",
    tags: ["Cybersecurity", "Network Security", "Penetration Testing"],
    salary: "$140K - $190K",
    type: "Full-time",
  },
  {
    id: 10,
    jobRole: "AI/ML Engineer",
    company: "Quora",
    companyDescription: "Knowledge-sharing and Q&A platform",
    logo: "/covers/quora.png",
    location: "Mountain View, CA (Remote)",
    tags: ["Machine Learning", "NLP", "TensorFlow", "PyTorch"],
    salary: "$160K - $220K",
    type: "Full-time",
  },
];
